"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Check, ChevronDown, Edit3, FileText, RefreshCw, Sparkles } from "lucide-react";
import { PageIntro, StatusBadge } from "../_components/dashboard-shell";

const views = ["Front view", "Back view", "Side view"];

export default function DesignPage() {
  return <div className="design-page"><PageIntro eyebrow="Create design / Oversized textured overshirt" title="Design workspace." description="Explore the current concept from every angle, then refine the direction before approval." action={<StatusBadge tone="accent">Concept preview</StatusBadge>} /><div className="design-layout"><aside className="requirements-panel"><div className="workspace-panel-heading"><span className="dashboard-eyebrow">Current brief</span><button aria-label="Edit brief"><Edit3 size={15} /></button></div><h3>Oversized textured<br /><em>overshirt</em></h3><p className="panel-muted">A relaxed utility layer with considered construction and a tactile finish.</p><div className="requirement-list"><div><span>Style</span><strong>Modern utility</strong></div><div><span>Fit</span><strong>Relaxed / oversized</strong></div><div><span>Fabric</span><strong>Cotton twill / 280 GSM</strong></div><div><span>Color</span><strong>Mineral green</strong></div><div><span>Season</span><strong>Spring / Summer 2025</strong></div></div><Link className="edit-brief-link" href="/dashboard/projects/new">Edit requirements <ChevronDown size={14} /></Link></aside><section className="generation-workspace"><div className="workspace-toolbar"><div><span className="dashboard-eyebrow">Generated concept / 01</span><h3>Utility overshirt / Mineral</h3></div><span className="workspace-date">Example concept · 08 Sep 2025</span></div><div className="design-views">{views.map((view, index) => <motion.div className={`design-view design-view-${index}`} key={view} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .12 }}><div className="view-art"><div className="placeholder-garment"><span /><i /><b /></div><small>AI VISUAL PLACEHOLDER</small></div><strong>{view}</strong></motion.div>)}</div><div className="generation-footer"><p><Sparkles size={15} /> Visual generation is not connected yet. This is a preview of the future workspace.</p><div className="workspace-actions"><button className="outline-button"><RefreshCw size={15} /> Regenerate</button><button className="outline-button"><Edit3 size={15} /> Edit design</button><button className="dashboard-primary-button"><Check size={15} /> Approve design</button><button className="dashboard-primary-button tech-action"><FileText size={15} /> Create tech-pack</button></div></div></section></div></div>;
}